---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: community.general
  - name: community.postgresql
roles:
  - name: trombik.git
  - name: trombik.postgresql
  - name: trombik.sysctl
  - name: trombik.redis
  - name: trombik.supervisor
  - name: trombik.haproxy
  - name: trombik.language_ruby
  - name: trombik.fab_manager
