---

- name: Create certs directory for haproxy
  ansible.builtin.file:
    path: /usr/local/etc/ssl/haproxy
    owner: www
    group: wheel
    mode: "0755"
    state: directory

- name: Copy TLS certs
  ansible.builtin.copy:
    src: files/fab.mkrsgh.org.pem
    dest: /usr/local/etc/ssl/haproxy/
    owner: www
    group: wheel
    mode: "0460"
