---

- name: Create certs directory for haproxy
  ansible.builtin.file:
    path: "{{ project_haproxy_cert_dir }}"
    owner: www
    group: wheel
    mode: "0755"
    state: directory

- name: Copy TLS certs
  ansible.builtin.copy:
    src: "files/{{ project_fab_manager_cert_file }}"
    dest: "{{ project_haproxy_cert_dir }}/"
    owner: www
    group: wheel
    mode: "0460"
