---

- hosts:
    - fab
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  pre_tasks:
    - ansible.builtin.debug:
        var: hostvars[inventory_hostname]
  roles:
    - role: trombik.git
    - role: trombik.git
    - role: trombik.sysctl
    - role: trombik.postgresql
    - role: trombik.redis
    - role: trombik.language_ruby
    - role: trombik.fab_manager
    - role: trombik.supervisor
    - role: trombik.haproxy
  vars:
